[package]
name = "bolide-runtime"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
num-bigint.workspace = true
num-traits.workspace = true
rust_decimal.workspace = true
once_cell.workspace = true
libloading = "0.8"
